' t
.TH XO7ASCII 1 "February 14, 2026" "" "User commands"
.SH NAME \"{{{roff}}}\"{{{
xo7ascii \- Microsoft Basic for 8-bit Canon X-07 program files detokenizer 
.\"}}}
.SH SYNOPSIS \"{{{
.ad l
.B to7ascii < tokenized.bas > listing.txt
.ad b
.\"}}}
.SH DESCRIPTION \"{{{
.SS "Introduction" \"{{{
.B xo7ascii
is a detokenizer for Microsoft Basic for Canon X-07 (an early portable
computer) program
files. \fBxo7ascii\fP reads 
on standard input a  Basic file saved in tokenized format and outputs  
the Basic program in ASCII format on standard output. The program may then
be used with a Unix traditional Basic interpreter such as
\fBbwbasic(1)\fP,\fPbas(1)\fP or \fBblassic(1)\fP. 
.\"}}}

.SH SEE ALSO \"{{{
cpmascii(1) gwascii(1) trs80ascii(1) bwbasic(1) bas(1) blassic(1) 
\"}}} 
.SH AUTHOR \"{{{
This program is copyright 2026. 
.PP
This program is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.
.PP
You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, write to the Free Software Foundation,
Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
.\"}}}
.SH HISTORY \"{{{
The program \fBgwbasic\fP written by Christian A. Ratliff
was a detokenizer for GW-Basic, the IBM-PC Basic interpreter. The
present program is inspired by it, but given the much simpler
structure of tokenized Basic on the X-07 it is written as a very
simple Unix filter. 
.\"}}}
